---
- name: Populate NetBox DataBase
  hosts: INTERFACE_TEMPLATES
  gather_facts: no
  vars:
    ansible_connection: local
  tasks:
    - import_role:
        name: build_netbox_db
        tasks_from: create_interface_template.yml