- name: "Create Device Platforms"
  netbox.netbox.netbox_platform:
    netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    data:
      name: "{{ device }}"
  loop: "{{ device_types | map(attribute='platform') | list | unique }}"
  loop_control:
    loop_var: device
  run_once: yes